merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    # admin
    path('admin/', admin.site.urls),

    path('hello/', views.hello),
    path('about-us/', views.about_us, name='about-us'),

    # listings
    path('listings/', views.listing_list, name='listing-list'),
    path('listings/<int:id>/', views.listing_detail, name='listing-detail'),
    path('listings/add/', views.listing_create, name='listing-create'),
    path('listings/<int:id>/change', views.listing_change, name='listing-change'),
    path('listings/<int:id>/delete', views.listing_delete, name='listing-delete'),
    
    # bands
    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:id>/', views.band_detail, name='band-detail'),
    path('bands/add/', views.band_create,name='band-create'),
    path('bands/<int:id>/change/', views.band_change, name='band-change'),
    path('bands/<int:id>/delete', views.band_delete, name='band-delete'),

    # contact
    path('contact/', views.contact, name='contact'),    
    path('contact/email-sent/', views.email_sent, name='email-sent'),
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

class Band(models.Model):

    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices,max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
        validators=[MinValueValidator(1900),MaxValueValidator(2024)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True,blank=True)
    

    def __str__(self):
        return f'{self.name}'
    

class Listing(models.Model):

    class Type(models.TextChoices):
        MISC = 'Misc'
        SIMPLE = 'Simple'
        DOUBLE = 'Double'

    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=100)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(
        validators=[MinValueValidator(1900),MaxValueValidator(2024)]
    )
    type = models.fields.CharField(choices=Type.choices,max_length=7)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

merchex/listings/forms.py
from django import forms

from listings.models import Band, Listing

class ContactUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)

class BandForm(forms.ModelForm):

    class Meta:
        model = Band
        # fields = '__all__'
        exclude = ('active', 'official_homepage')

class ListingForm(forms.ModelForm):

    class Meta:
        model = Listing
        # fields = '__all__'
        exclude = ('sold',)

merchex/listings/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail

from listings.models import Band, Listing
from listings.forms import BandForm, ContactUsForm, ListingForm

def hello(request):
    bands = Band.objects.all()
    return render(request,'listings/hello.html', 
                {'bands': bands})

def about_us(request):
    return render(request, 'listings/about.html')

# LISTINGS -----------------
def listing_list(request):
    listings = Listing.objects.all()
    return render(request, 
                'listings/listing_list.html',
                {'listings':listings})

def listing_detail(request, id):
    listing = Listing.objects.get(id=id)
    return render(request,
                'listings/listing_detail.html',
                {'listing':listing}) 
def listing_create(request):
    if request.method == 'POST':
        form = ListingForm(request.POST)
        if form.is_valid():
            listing = form.save()
            return redirect('listing-detail', listing.id)
    
    else:
        form = ListingForm()

    return render(request,
                'listings/listing_create.html',
                {'form':form})

def listing_change(request, id):
    listing = Listing.objects.get(id=id)
    
    if request.method == 'POST':
        form = ListingForm(request.POST, instance=listing)
        if form.is_valid():
            form.save()

            return redirect('listing-detail', listing.id)
    else:
        form = ListingForm(instance=listing)

    return render(request,
                'listings/listing_change.html',
                {'form':form})

def listing_delete(request, id):
    listing = Listing.objects.get(id=id)

    if request.method == 'POST':
        listing.delete()
        return redirect('listing-list')
    
    return render(request,
                'listings/listing_delete.html',
                {'listing':listing})

# BANDS --------------------
def band_list(request):
    bands = Band.objects.all()
    return render(request,
                'listings/band_list.html',
                {'bands':bands})

def band_detail(request, id):
    band = Band.objects.get(id=id)

    listings = Listing.objects.all()
    return render(request,
                'listings/band_detail.html',
                {'band': band,'listings':listings})

def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            band = form.save()
            return redirect('band-detail', band.id)
        
    else:
        form = BandForm()
    
    return render(request, 
                'listings/band_create.html',
                {'form':form})

def band_change(request, id):
    band = Band.objects.get(id=id)
    
    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            form.save()

            return redirect('band-detail', band.id)
    else:
        form = BandForm(instance=band)

    return render(request,
                'listings/band_change.html',
                {'form':form})
    
def band_delete(request, id):
    band = Band.objects.get(id=id)

    if request.method == 'POST':
        band.delete()
        return redirect('band-list')
    
    return render(request,
                'listings/band_delete.html',
                {'band':band})

# CONTACT ---------------
def contact(request):
    return render(request, 'listings/contact.html')

def contact(request):
    """Vue du contact/"""
    if request.method == 'POST':
        form = ContactUsForm(request.POST)

        if form.is_valid():
            send_mail(
                subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
                message=form.cleaned_data['message'],
                from_email=form.cleaned_data['email'],
                recipient_list=['admin@merchex.xyz'],
            )
            return redirect('email-sent/') # Confirmation d'envoi
    else:
        form=ContactUsForm()

    return render(request,
                'listings/contact.html',
                {'form': form})

def email_sent(request):
    return render(request, 'listings/email_sent.html')

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}
{% block content %}

    <p>This is the about page.</p>
{% endblock %}

merchex/listings/templates/listings/band_change.html
{% extends 'listings/base.html' %}
{% block content %}

<h1>Modifier un groupe</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}
{% block content %}

<h1>Créer un nouveau gorupe</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}
{% block content %}

<h1>Supprimer le groupe</h1>

<p>Etes-vous sûr de vouloir supprimer le groupe : {{ band.name }} ??</p>

<form action="" method="post">
    {% csrf_token %}
<input  type="submit" value="Supprimer">
</form>

{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}
{% block content %}
<h2>{{ band.name }}</h2>

<ul>
    <li>Genre : {{ band.get_genre_display }}</li>
    <li>Année de formation : {{ band.year_formed }}</li>
    <li>Actif : {{ band.active|yesno }}</li>
    {% if band.official_homepage %}
    <li><a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>
    {% endif %}
    
    {% if listings.count != 0 %}
        {% for listing in listings %}
        {% if band.id == listing.band.id %}
            <li>Annonce(s) du groupe :</li>
            <ul>
                <li><a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a></li>
            </ul>
        {% endif %}
        {% endfor %}          
    {% endif %}
</ul>

<p>{{ band.biography }}</p>

<a href="{% url 'band-change' band.id %}">[Modifier ce groupe]</a>
<a href="{% url 'band-delete' band.id %}">[Supprimer ce groupe]</a>
<a href="{% url 'band-list' %}">[Retour à tous les groupes]</a>
{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}
{% block content %}
<h1>Groupes</h1>

<ul>
{% for band in bands %}
<li>
    <a href="{% url 'band-detail' band.id %}">{{ band.name }}</a>
    - <a href="{% url 'band-change' band.id %}">[Modifier]</a>
</li>

{% endfor %}
</ul>

<a href="{% url 'band-create' %}">[Créer un nouveau groupe]</a>
{% endblock %}

merchex/listings/templates/listings/base.html
{% load static %}
<html>
    <head>
       <title>Merchex</title>
       <link rel="stylesheet" href="{% static 'listings/style.css' %}"/>
    </head>
    <body>
        <nav>
            <a href="{% url 'band-list' %}">Groupes |</a>
            <a href="{% url 'listing-list' %}">Annonces |</a>
            <a href="{% url 'contact' %}">Contact |</a>
            <a href="{% url 'about-us' %}">A propos |</a>
        </nav>
        {% block content %}{% endblock %}

    </body>
</html>

merchex/listings/templates/listings/email_sent.html
{% extends 'listings/base.html' %}
{% block content %}

<h2>L'email à été envoyé</h2>


{% endblock %}

merchex/listings/templates/listings/hello.html
{% extends 'listings/base.html' %}
{% block content %}

<p>Groupes<p>

<ul>
    {% for band in bands %}

    <li>
        {{ band.name}}
    </li>
    {% endfor %}
</ul>

{% endblock %}

merchex/listings/templates/listings/listing_change.html
{% extends 'listings/base.html' %}
{% block content %}

<h1>Modifier un groupe</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/listing_create.html
{% extends 'listings/base.html' %}
{% block content %}

<h1>Créer une nouvelle annonce</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/listing_delete.html
{% extends 'listings/base.html' %}
{% block content %}

<h1>Supprimer l'annonce</h1>

<p>Etes-vous sûr de vouloir supprimer l'annonce : {{ listing.band }} ?</p>

<form action="" method="post">
    {% csrf_token %}
<input  type="submit" value="Supprimer">
</form>

{% endblock %}

merchex/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}
{% block content %}
<h2>{{ listing.title }}</h2>
<p>{{ listing.description }}</p>
<ul>
    <li>Type de billet : {{ listing.type }} </li>
    <li>Année de vente : {{ listing.year }}</li>
    <li>Vendu : {{ listing.sold|yesno }}</li>
</ul>

<p>Ce billet est uniquement valable pour le groupe : <a href="{% url 'band-detail' listing.band.id %}">{{ listing.band }}</a></p>

<a href="{% url 'listing-change' listing.id %}">[Modifer cette annonce]</a>
<a href="{% url 'listing-delete' listing.id %}">[Supprimer cette annonce]</a>
<a href="{% url 'listing-list' %}">[Retour à toutes les annonces]</a>
{% endblock %}

merchex/listings/templates/listings/listing_list.html
{% extends 'listings/base.html' %}
{% block content %}
<h1>Annonces</h1>

<ul>
{% for listing in listings %}
<li>
    <a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a>
    -   <a href="{% url 'listing-change' listing.id %}">[Modifier]</a>
</li>
{% endfor %}
</ul>

<a href="{% url 'listing-create' %}">[Créer une nouvelle annonce]</a>
{% endblock %}